# Generated by Django 6.0.1 on 2026-08-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turforaapp', '0002_rename_fullname_playerdetail_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdetail',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
