# Generated by Django 6.0.1 on 2026-08-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turforaapp', '0003_playerdetail_is_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('turf_type', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='turf_images/')),
                ('description', models.TextField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_facilities', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
    ]
