# Generated by Django 6.0.1 on 2026-08-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turforaapp', '0004_turf'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turf',
            name='closing_time',
            field=models.TimeField(default='22:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turf',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='opening_time',
            field=models.TimeField(default='06:00:00'),
            preserve_default=False,
        ),
    ]
