# Generated by Django 6.0.1 on 2026-08-29 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turforaapp', '0005_turf_address_turf_closing_time_turf_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turforaapp.playerdetail')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turforaapp.turf')),
            ],
        ),
    ]
