# Generated by Django 6.0.1 on 2026-09-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turforaapp', '0007_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='turforaapp.booking')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turforaapp.playerdetail')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turforaapp.turf')),
            ],
        ),
    ]
