# Generated by Django 6.0.1 on 2026-09-10 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turforaapp', '0009_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turforaapp.turf')),
            ],
        ),
        migrations.CreateModel(
            name='TurfHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('maintenance', 'Maintenance'), ('holiday', 'Holiday'), ('inactive', 'Inactive')], max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turforaapp.turf')),
            ],
        ),
        migrations.CreateModel(
            name='TurfSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turforaapp.turf')),
            ],
        ),
    ]
