# Generated by Django 6.0.1 on 2026-09-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turforaapp', '0010_blockedslot_turfholiday_turfslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
