# Generated by Django 6.0.1 on 2026-09-11 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turforaapp', '0011_review_is_flagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('confirmation', 'Booking Confirmation'), ('cancellation', 'Booking Cancellation'), ('reminder', 'Booking Reminder'), ('status_change', 'Booking Status Change')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turforaapp.booking')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turforaapp.playerdetail')),
            ],
        ),
    ]
